# Generated by Django 5.2.17 on 2026-08-07 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('movement', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('quartz', 'Quartz'), ('spring_drive', 'Spring Drive')], max_length=50)),
                ('case_size', models.CharField(max_length=50)),
                ('case_material', models.CharField(max_length=100)),
                ('dial_color', models.CharField(max_length=100)),
                ('strap_material', models.CharField(max_length=100)),
                ('water_resistance', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='watches.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watches', to='watches.category')),
            ],
        ),
        migrations.CreateModel(
            name='WatchImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='watches/')),
                ('is_primary', models.BooleanField(default=False)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='watches.watch')),
            ],
        ),
    ]
