# Generated by Django 5.2.17 on 2026-08-07 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collections/')),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='watchimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='brand',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='watch',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], default='unisex', max_length=20),
        ),
        migrations.AddField(
            model_name='watch',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watch',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watch',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watch',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='watch',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watch',
            name='stock_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='watch',
            name='warranty_period',
            field=models.CharField(default='2 Years', max_length=50),
        ),
        migrations.AddField(
            model_name='watchimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watch',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watches', to='watches.collection'),
        ),
        migrations.CreateModel(
            name='WatchVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='watches/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='watches/video_thumbnails/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='watches.watch')),
            ],
        ),
    ]
