# Generated by Django 5.2.17 on 2026-08-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0005_stocknotify'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='availability',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('in_stock', 'In stock'), ('pre_order', 'Pre-order'), ('out_of_stock', 'Out of stock'), ('discontinued', 'Discontinued')], max_length=20),
        ),
        migrations.AddField(
            model_name='watch',
            name='bezel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='bracelet_material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='caliber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='case_diameter_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='case_shape',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='case_thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='clasp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='crystal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='currency',
            field=models.CharField(default='CHF', max_length=3),
        ),
        migrations.AddField(
            model_name='watch',
            name='data_quality',
            field=models.CharField(default='ok', max_length=16),
        ),
        migrations.AddField(
            model_name='watch',
            name='functions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='image_attribution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='watch',
            name='image_license',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='watch',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='limited_edition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watch',
            name='lug_to_lug_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='movement_type',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('mechanical', 'Mechanical'), ('quartz', 'Quartz'), ('solar', 'Solar'), ('hybrid', 'Hybrid')], max_length=50),
        ),
        migrations.AddField(
            model_name='watch',
            name='power_reserve',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='watch',
            name='sku',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='watch',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='watch',
            name='source_product_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='watch',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='sources',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='water_resistance_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='watch',
            constraint=models.UniqueConstraint(condition=models.Q(('source', ''), _negated=True), fields=('source', 'source_product_id'), name='uniq_watch_source_product'),
        ),
    ]
