# Generated by Django 5.2.17 on 2026-08-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0006_watch_availability_watch_bezel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
