# Generated by Django 5.2.17 on 2026-08-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0007_alter_watch_reference_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=60)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('partial', 'Partial'), ('failed', 'Failed')], default='ok', max_length=10)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('products_found', models.PositiveIntegerField(default=0)),
                ('products_parsed', models.PositiveIntegerField(default=0)),
                ('inserted', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('duplicates', models.PositiveIntegerField(default=0)),
                ('invalid', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('dry_run', models.BooleanField(default=False)),
                ('errors', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='watches_ing_source_d66b34_idx')],
            },
        ),
    ]
